server:
  port: ${SQLOJ_PORT:10100}

spring:
  jackson:
    time-zone: Asia/Shanghai
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: ${SQLOJ_DB_URL:jdbc:mariadb://judge-mariadb-database:3306/}
    username: ${SQLOJ_DB_USER:root}
    password: ${SQLOJ_DB_PASSWORD:sy123456}

mybatis:
  mapper-locations: classpath:mapping/*Mapping.xml
  type-aliases-package: pers.sy.sqloj.entity
