version: '3'

services:
  mariadb:
    image: mariadb
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - ./dbdata:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      MYSQL_ROOT_PASSWORD: sy123456
      MYSQL_USER: test
      MYSQL_PASSWORD: sy123456
      MYSQL_INITDB_SKIP_TZINFO: 1
